### PR TITLE
Fix build for nightly

### PR DESCRIPTION
**Pull request by dzbarsky**

### CODE REVIEW

**Comment by gnzlbg** [comment]
@dzbarsky did they rename it back? You have a link to the PR ?

**Comment by gnzlbg** [comment]
See https://github.com/SkylerLipthay/interpolate_idents/pull/39

**Comment by gnzlbg** [comment]
I can't reproduce, are you sure you are using the latests nightly ? What's your `rustc --version` ? rustc 1.30.0-nightly (a8c11d216 2018-09-06) ?

**Comment by dzbarsky** [comment]
Ah, I am a bit behind you on the nightly upgrade train. Sorry!

**Pull request closed without merging**
